pdf:
	pandoc Example_presentation.md -t beamer -V aspectratio=169 -V theme:metropolis -o Example_presentation.pdf

html:
	 pandoc Example_presentation.md -t revealjs --standalone -o Example_presentation.html
